version: '3.5'
services:
  app: # Java Springboot Backend  
    build: .
    container_name: storage-application
    ports:
      - 8085:8080
    depends_on:
      - "database"
    networks:
      - storage_db_network
  database:
    build:
        context: database
    image: postgres-14-database
    container_name: postgres14.2-db-myfreezer 
    restart: always
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
        - 5434:5432
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    labels:
      author: "Ahmed Marzook"
volumes:
  database-data: # named volumes can be managed easier using docker-compose
networks:
  storage_db_network:
